export const coinPlaceholder = require('./coin-placeholder.png');
export const spinner = require('./spinner.png');
export const downLogo = require('./logo.png');
export const background = require('./background.png');
export const loadingBackground = require('./loading_bg.png');
export const screenStub = require('./screen-stub.png');
export const simpleLogo = require('./simple-logo.png');
export const keyLogo = require('./key-logo.png');
export const walletLogo = require('./wallet-logo.png');
export const wavesLeft = require('./waves-left.png');
export const wavesRight = require('./waves-right.png');
export const balanceHeader = require('./balance-header-bg.png');
export const nftPlaceholder1 = require('./ntf_placeholder-1.png');
export const nftPlaceholder2 = require('./ntf_placeholder-2.png');
export const nftPlaceholder3 = require('./ntf_placeholder-3.png');
export const nftCheck = require('./nft_check.png');
export const nftArrow = require('./ntf_arrow.png');
export const nftLogo = require('./ntf_logo.png');
export const upButton = require('./up-button.png');
export const downButton = require('./down-button.png');

export * from './earn-stubs';
