require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
platform :ios, '12.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'slaviWalletMobile' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'

  target 'slaviWalletMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
end

target 'slaviWalletMobile-tvOS' do
  # Pods for slaviWalletMobile-tvOS

  target 'slaviWalletMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

config = use_native_modules!

use_react_native!(
:path => config[:reactNativePath],
# to enable hermes on iOS, change `false` to `true` and then install pods
:hermes_enabled => false
)

# you should disable the next line.
use_flipper!()
