platform :ios, '10.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'slaviWalletMobile' do
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'

  target 'slaviWalletMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
end

target 'slaviWalletMobile-tvOS' do
  # Pods for slaviWalletMobile-tvOS

  target 'slaviWalletMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

config = use_native_modules!

use_react_native!(
:path => config[:reactNativePath],
# to enable hermes on iOS, change `false` to `true` and then install pods
:hermes_enabled => false
)

# you should disable the next line.
#use_flipper!()

ENVFILES = {
  'Debug' => '$(PODS_ROOT)/../../.env.development',
  'Release' => '$(PODS_ROOT)/../../.env.production',
}
post_install do |installer|
    react_native_post_install(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        if target.name == 'react-native-config'
          config.build_settings['ENVFILE'] = ENVFILES[config.name]
        end
      end
    end
end
