require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")

def node_require(script)
# Resolve script with node to allow for hoisting
    require Pod::Executable.execute_command('node', ['-p',
       "require.resolve(
       '#{script}',
       {paths: [process.argv[1]]},
     )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
 'Camera',
])

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

use_frameworks! :linkage => :static
# right after `use_frameworks! :linkage => :static`
$RNFirebaseAsStaticFramework = true

target 'slaviWalletMobile' do
  use_expo_modules!

  pod 'SRSRadialGradient', :path => '../node_modules/react-native-radial-gradient/ios'

  pod 'react-native-restart', :path => '../node_modules/react-native-restart'

  pod 'RNFBMessaging', :path => '../node_modules/@react-native-firebase/messaging'

  pod 'RNFBAnalytics', :path => '../node_modules/@react-native-firebase/analytics'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBCrashlytics', :path => '../node_modules/@react-native-firebase/crashlytics'

  pod 'RNFBPerf', :path => '../node_modules/@react-native-firebase/perf'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'RNFBDynamicLinks', :path => '../node_modules/@react-native-firebase/dynamic-links'

  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
  pod 'react-native-config', :path => '../node_modules/react-native-config'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'slaviWalletMobileTests' do
    inherit! :complete
    # Pods for testing
  end

  use_native_modules!
end

target 'slaviWalletMobile-tvOS' do
  # Pods for slaviWalletMobile-tvOS

  target 'slaviWalletMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

config = use_native_modules!

# Flags change depending on the env values.
flags = get_default_flags()

use_react_native!(
    :path => config[:reactNativePath],

    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
#     :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
)

# you should disable the next line.
# use_flipper!()

post_install do |installer|
# https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
react_native_post_install(
 installer,
 config[:reactNativePath],
 :mac_catalyst_enabled => false
)
    installer.pods_project.build_configurations.each do |config| config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] =  "arm64"
    end
end
